import { Inter } from "next/font/google";
import "./globals.css";

import AuthProvider from "./context/auth";
import Navbar from "./components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast"

export const metadata = {
  title: "ChefHub",
  description: "Generated by Mahbub Ahmed Turza",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <Toaster />
        </body>
      </html>
    </AuthProvider>
  );
}
